apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: light-6563a38c-618f-48c0-ab15-46221fdfac9f-certificate
  namespace: light-6563a38c-618f-48c0-ab15-46221fdfac9f
spec:
  secretName: light-6563a38c-618f-48c0-ab15-46221fdfac9f-secret-tls
  commonName: lyna-light.tinhlgkiddy.fun
  dnsNames:
  - lyna-light.tinhlgkiddy.fun
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
